### ISSUE TITLE
Could not pass event PlayerInteractEvent to Movecraft-Repair

### ISSUE THREAD

**Issue by TomLewis** [APDevTeam/Movecraft-Repair#20]
Ahoy! After ticket #19 I used the Firework to create a state for a ship, which created a schematic! Horray!
But then after trying every method I could think of to try and get it to restore, I checked the logs and saw that it was throwing an error when it was trying to fire the Restore function.

I would assume this is specific to FAWE or being 1.18.2? 
There was no feedback in chat when interacting.

```
[09:45:30] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Movecraft-Repair v1.0.0_beta-2
java.lang.NoSuchMethodError: 'void com.sk89q.worldedit.world.block.BlockType.<init>(java.lang.String)'
	at net.countercraft.movecraft.repair.util.WEUtils.getBlockContents(WEUtils.java:170) ~[Movecraft-Repair.jar:?]
	at net.countercraft.movecraft.repair.types.RepairState.execute(RepairState.java:144) ~[Movecraft-Repair.jar:?]
	at net.countercraft.movecraft.repair.RepairSign.createProtoRepair(RepairSign.java:157) ~[Movecraft-Repair.jar:?]
	at net.countercraft.movecraft.repair.RepairSign.onRightClick(RepairSign.java:98) ~[Movecraft-Repair.jar:?]
	at net.countercraft.movecraft.repair.RepairSign.onSignClick(RepairSign.java:82) ~[Movecraft-Repair.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor673.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:git-Purpur-1632]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:565) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1925) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1375) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1257) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by TylerS1066** [comment]
I've recently tested the following combinations without any issues like this (all with Movecraft-Repair bc6305d7013075c2b837f9286c4ce16e54d8f2ea), so I suspect it's specific to FAWE:
- Paper 1.14.4 with WorldEdit 7.2.13
- Paper 1.16.5 with WorldEdit 7.2.13
- Paper 1.16.5 with WorldEdit 7.2.14 & AsyncWorldEdit 3.9.4

I suspect that FAWE failed to fully implement the WorldEdit API (specifically `void com.sk89q.worldedit.world.block.BlockType.<init>(java.lang.String)`, and that is why this exception happens.  You'll have to contact their developers and ask them to fix their implementation of the WorldEdit API.
