### ISSUE TITLE
1.20.4 Errors

### ISSUE THREAD

**Issue by Nikkilectric** [APDevTeam/Movecraft-Repair#33]
When a player tries to use a repair sign on the [latest](https://github.com/APDevTeam/Movecraft-Repair/actions/runs/9140869143) dev build, this error appears:

```[21:30:48 ERROR]: Could not pass event PlayerInteractEvent to Movecraft-Repair v1.0.0_beta-3
java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because "component" is null
at net.countercraft.movecraft.repair.util.WEUtils.getSignTextFromMap(WEUtils.java:242) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.util.WEUtils.getSignTextFromJSON(WEUtils.java:220) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.util.WEUtils.getBlockSignLines(WEUtils.java:207) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.types.RepairState.execute(RepairState.java:137) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.RepairSign.createProtoRepair(RepairSign.java:158) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.RepairSign.onRightClick(RepairSign.java:98) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at net.countercraft.movecraft.repair.RepairSign.onSignClick(RepairSign.java:83) ~[Movecraft-Repair_6db16c61234b620e5772692078365270691790c1.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor609.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:git-Paper-496]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.4.jar:git-Paper-496]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.4.jar:git-Paper-496]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:594) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:536) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1935) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:54) ~[?:?]
at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:149) ~[?:?]
at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1465) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:123) ~[?:?]
at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1442) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1365) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:133) ~[?:?]
at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1343) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1232) ~[paper-1.20.4.jar:git-Paper-496]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
at java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by Nikkilectric** [comment]
Solved in your most recent PR. Sorry about that.
