### ISSUE TITLE
Error: Entry #chests is not a valid tag!

### ISSUE THREAD

**Issue by ChrissW-R1** [APDevTeam/Movecraft-Repair#50]
Can't start the plugin in PaperMC 1.21.1 Build 128.

```
[Server thread/INFO]: [Movecraft-Repair] Enabling Movecraft-Repair v1.0.0_beta-6
[Server thread/INFO]: [Movecraft-Repair] Found a compatible Vault plugin. Enabling Vault integration.
[Server thread/INFO]: [Movecraft-Repair] Found a compatible version of WorldEdit. Enabling WorldEdit integration.
[Server thread/ERROR]: Error occurred while enabling Movecraft-Repair v1.0.0_beta-6 (Is it up to date?)
java.lang.IllegalArgumentException: Entry #chests is not a valid tag!
	at Movecraft-8.0.0_beta-5.jar/net.countercraft.movecraft.util.Tags.parseBlockRegistry(Tags.java:71) ~[Movecraft-8.0.0_beta-5.jar:?]
	at Movecraft-Repair_1.0.0_beta-6.jar/net.countercraft.movecraft.repair.MovecraftRepair.loadConfig(MovecraftRepair.java:140) ~[Movecraft-Repair_1.0.0_beta-6.jar:?]
	at Movecraft-Repair_1.0.0_beta-6.jar/net.countercraft.movecraft.repair.MovecraftRepair.onEnable(MovecraftRepair.java:89) ~[Movecraft-Repair_1.0.0_beta-6.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:641) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:590) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:753) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:515) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1214) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.1.jar:1.21.1-128-d348cb8]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[Server thread/INFO]: [Movecraft-Repair] Disabling Movecraft-Repair v1.0.0_beta-6
```

**Comment by TylerS1066** [comment]
As described on the [FAQ in the wiki](https://github.com/APDevTeam/Movecraft/wiki/Frequently-Asked-Questions#movecraft-8-or-its-addons-wont-load) this is likely due to the datapack not being loaded.

**Comment by ChrissW-R1** [comment]
The datapack was enabled. But it looks like after a backup the datapack has changed and should be rebuilt.
So after removing the ZIP file under `world/movecraft-data.zip` and restarting the server, the error was gone.
